services:
  - type: web
    name: discord-bot
    env: node
    buildCommand: npm install
    startCommand: bash start.sh
    plan: free
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: NODE_ENV
        value: production
